import { RainbowKitProvider, Theme } from '@rainbow-me/rainbowkit';
export const auraAnalyticsWagmiTheme: Theme = {
    blurs: {
        modalOverlay: '...',
    },
    colors: {
        accentColor: '...',
        accentColorForeground: '...',
        actionButtonBorder: '...',
        actionButtonBorderMobile: '...',
        actionButtonSecondaryBackground: '...',
        closeButton: '...',
        closeButtonBackground: '...',
        connectButtonBackground: '...',
        connectButtonBackgroundError: '...',
        connectButtonInnerBackground: '...',
        connectButtonText: '...',
        connectButtonTextError: '...',
        connectionIndicator: '...',
        downloadBottomCardBackground: '...',
        downloadTopCardBackground: '...',
        error: '...',
        generalBorder: '...',
        generalBorderDim: '...',
        menuItemBackground: '...',
        modalBackdrop: '...',
        modalBackground: '...',
        modalBorder: '...',
        modalText: '...',
        modalTextDim: '...',
        modalTextSecondary: '...',
        profileAction: '...',
        profileActionHover: '...',
        profileForeground: '...',
        selectedOptionBorder: '...',
        standby: '...',
    },
    fonts: {
        body: '...',
    },
    radii: {
        actionButton: '...',
        connectButton: '...',
        menuButton: '...',
        modal: '...',
        modalMobile: '...',
    },
    shadows: {
        connectButton: '...',
        dialog: '...',
        profileDetailsAction: '...',
        selectedOption: '...',
        selectedWallet: '...',
        walletLogo: '...',
    },
};